# Generated by Django 3.0.3 on 2020-03-18 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('crime', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('embedding', models.CharField(max_length=20000)),
                ('photo', models.ImageField(upload_to='photos/')),
            ],
        ),
    ]
